INSERT INTO MEMBER
VALUE(  MEMBER_NUMBER,
        MEMBER_ID,
        MEMBER_PASSWORD,
        MEMBER_NAME,
        MEMBER_EMAIL,
        MEMBER_BIRTH_DATE,
        MEMBER_PHONE_NUMBER,
        MEMBER_MONEY,
        MEMBER_GENDER,
        MEMBER_CREATE_DATE,
        MEMBER_MODIFY_DATE)
VALUES(MEMBER_NUMBER_SEQ.NEXTVAL, 'kimj92', 'jeongsu9292!', '김정수', 'kimj92@ezen.com', '1992-01-30', '01014351668', 0, 'M', SYSDATE, SYSDATE);
INSERT INTO MEMBER
VALUES(MEMBER_NUMBER_SEQ.NEXTVAL, 'rudtj22', 'sksmsrudtj22@', '박경서', 'rudtj22@ezen.com', '1995-08-22', '01014247683', 0, 'F', SYSDATE, SYSDATE);
INSERT INTO MEMBER
VALUES(MEMBER_NUMBER_SEQ.NEXTVAL, 'seok2256', 'anwlro2256*', '강현석', 'seok2256@ezen.com', '1988-05-19', '01089652256', 0, 'M', SYSDATE, SYSDATE);
INSERT ALL 
	into MEMBER(MEMBER_NUMBER,
                MEMBER_ID,
                MEMBER_PASSWORD,
                MEMBER_NAME,
                MEMBER_EMAIL,
                MEMBER_BIRTH_DATE,
                MEMBER_PHONE_NUMBER,
                MEMBER_MONEY,
                MEMBER_GENDER,
                MEMBER_CREATE_DATE,
                MEMBER_MODIFY_DATE) 
    values (MEMBER_NUMBER_SEQ.NEXTVAL, 'lsw0909', 'tjsdn99!@', '이선우', 'lsw0909@ezen.com', '1999-09-09', '01088460576', 0, 'F', SYSDATE, SYSDATE)
	into PREFER_GENRE(
                        PREFER_GENRE_NUMBER, 
                        PREFER_GENRE_FIRST, 
                        PREFER_GENRE_SECOND, 
                        PREFER_GENRE_THIRD, 
                        MEMBER_NUMBER) 
    values (PREFER_GENRE_NUMBER_SEQ.NEXTVAL, '공포', '코미디', '로맨스', MEMBER_NUMBER_SEQ.NEXTVAL)
select * from dual;

SELECT* FROM MEMBER;


INSERT INTO PREFER_GENRE
VALUE(PREFER_GENRE_NUMBER, PREFER_GENRE_FIRST, PREFER_GENRE_SECOND, PREFER_GENRE_THIRD, MEMBER_NUMBER)
VALUES(PREFER_GENRE_NUMBER_SEQ.NEXTVAL, '공포', '코미디', '로맨스', 1);
INSERT INTO PREFER_GENRE
VALUES(PREFER_GENRE_NUMBER_SEQ.NEXTVAL, '미스터리', '멜로', '뮤지컬', 2);
INSERT INTO PREFER_GENRE
VALUES(PREFER_GENRE_NUMBER_SEQ.NEXTVAL, 'SF', '범죄', '스릴러', 3);
INSERT INTO PREFER_GENRE
VALUES(PREFER_GENRE_NUMBER_SEQ.NEXTVAL, '액션', '스포츠', '전쟁', 4);
SELECT* FROM PREFER_GENRE;


INSERT INTO GENRE
VALUE(GENRE_NUMBER, GENRE_NAME)
VALUES(1, 'SF');
INSERT INTO GENRE
VALUES(2, '공포');
INSERT INTO GENRE
VALUES(3, '로맨스');
INSERT INTO GENRE
VALUES(4, '멜로');
INSERT INTO GENRE
VALUES(5, '뮤지컬');
INSERT INTO GENRE
VALUES(6, '범죄');
INSERT INTO GENRE
VALUES(7, '스릴러');
INSERT INTO GENRE
VALUES(8, '스포츠');
INSERT INTO GENRE
VALUES(9, '액션');
INSERT INTO GENRE
VALUES(10, '음악');
INSERT INTO GENRE
VALUES(11, '전쟁');
INSERT INTO GENRE
VALUES(12, '코미디');
INSERT INTO GENRE
VALUES(13, '판타지');
INSERT INTO GENRE
VALUES(14, '미스터리');
INSERT INTO GENRE
VALUES(15, '드라마');
INSERT INTO GENRE
VALUES(16, '애니메이션');
SELECT* FROM GENRE;


INSERT INTO MOVIE
VALUE(MOVIE_NUMBER, MOVIE_TITLE, MOVIE_SUMMARY, MOVIE_RELEASE_DATE, MOVIE_RUNTIME, MOVIE_PRICE, MOVIE_POSTER, MOVIE_PREVIEW, GENRE_NUMBER)
VALUES(MOVIE_NUMBER_SEQ.NEXTVAL, '잠', '행복한 신혼부부 ‘현수’(이선균)와 ‘수진’(정유미). 어느 날, 옆에 잠든 남편 ‘현수’가 이상한 말을 중얼거린다.', '2023-09-06', 94, 10000, 'https://i.namu.wiki/i/CShyZFGfn4Yjdj0J3H387gNPESrLdaVQOYfywG_NaLUaTh3N3tYhD2B-1x35eFJH_nKouqmIgo3foNoPxt2ESA.webp', 'https://tv.naver.com/v/39675900', 14);
INSERT INTO MOVIE
VALUES(MOVIE_NUMBER_SEQ.NEXTVAL, '콘크리트 유토피아', '“아파트는 주민의 것” 온 세상을 집어삼킨 대지진, 그리고 하루아침에 폐허가 된 서울. 모든 것이 무너졌지만 오직 황궁 아파트만은 그대로다.', '2023-08-09', 130, 10000, 'https://i.namu.wiki/i/UzpGwb3r9bgA71yBzP58V6IwqlBtXQZeeto9_v5QG-_m7A8Q_ai1aQdrF-XMlD2Xs7-lQiBGcS3Srr5eqemjT4FJ2USynqVOqKLdUnHOqfbxOVS37eBVSu5eSUHevtubf_0NVpJVGSwblhd0FDCYrg.webp', 'https://tv.naver.com/v/38045897', 15);
INSERT INTO MOVIE
VALUES(MOVIE_NUMBER_SEQ.NEXTVAL, '엘리멘탈', '불, 물, 공기, 흙 4개의 원소들이 살고 있는 ‘엘리멘트 시티’ 재치 있고 불처럼 열정 넘치는 ‘앰버’', '2023-06-14', 109, 11000, 'https://i.namu.wiki/i/UzpGwb3r9bgA71yBzP58V6IwqlBtXQZeeto9_v5QG-_m7A8Q_ai1aQdrF-XMlD2Xs7-lQiBGcS3Srr5eqemjT4FJ2USynqVOqKLdUnHOqfbxOVS37eBVSu5eSUHevtubf_0NVpJVGSwblhd0FDCYrg.webp', 'https://tv.naver.com/v/38045897', 16);
INSERT INTO MOVIE
VALUES(MOVIE_NUMBER_SEQ.NEXTVAL, '타겟', '중고거래로 범죄의 표적이 된 ‘수현’의 일상 속에서 벌어지는 서스펜스를 담은 스릴러', '2023-08-30', 101, 8000, 'https://i.namu.wiki/i/sBwdeekyyhtz1gqQhbtyBIasYGwbIr5FtaWXr9YZ_2xf7u3nAgjaIm3yKWCThEbeLALWz2_NqwqjmWef7eeznIsctSFgl_uLDg_w-1bBFKdsm1v8f8zVLFHO6SKpCmhXr_mCZGNfAld-Uz9UZSw3fw.webp', 'https://tv.naver.com/v/38045897', 15);
SELECT* FROM MOVIE;


INSERT INTO BOARD
VALUE(BOARD_NUMBER, BOARD_TITLE, BOARD_CONTENT, BOARD_CREATE_DATE, BOARD_HIT, MEMBER_NUMBER)
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '아 집가고싶다', '집에 가고싶은데 팀플 해야해', sysdate, 14, 1);
INSERT INTO BOARD
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '제목 추천 좀', '안녕하세요. 새로 가입했습니다^^', sysdate, 10, 2);
INSERT INTO BOARD
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '점메추', '오늘 점심 추천 받는다', sysdate, 12, 1);
INSERT INTO BOARD
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '등업 신청합니다', 'ㅈㄱㄴ', sysdate, 3, 1);
INSERT INTO BOARD
VALUES(BOARD_NUMBER_SEQ.NEXTVAL, '안녕하세요', '브라이튼여의도아파트 [브라이튼 여의도 아파트 vip 안내]', sysdate, 5, 3);
SELECT* FROM BOARD;


INSERT INTO HEART
VALUE(HEART_NUMBER, HEART_CHECK, MEMBER_NUMBER, MOVIE_NUMBER)
VALUES(HEART_NUMBER_SEQ.NEXTVAL, 'N', 1, 1);
INSERT INTO HEART
VALUES(HEART_NUMBER_SEQ.NEXTVAL, 'N', 2, 2);
INSERT INTO HEART
VALUES(HEART_NUMBER_SEQ.NEXTVAL, 'Y', 3, 2);
INSERT INTO HEART
VALUES(HEART_NUMBER_SEQ.NEXTVAL, 'Y', 4, 4);
SELECT* FROM HEART;


INSERT INTO WATCH
VALUE(WATCH_NUMBER, WATCH_CHECK, MEMBER_NUMBER, MOVIE_NUMBER)
VALUES(WATCH_NUMBER_SEQ.NEXTVAL, 'N', 1, 1);
INSERT INTO WATCH
VALUES(WATCH_NUMBER_SEQ.NEXTVAL, 'Y', 2, 2);
INSERT INTO WATCH
VALUES(WATCH_NUMBER_SEQ.NEXTVAL, 'N', 2, 2);
INSERT INTO WATCH
VALUES(WATCH_NUMBER_SEQ.NEXTVAL, 'N', 2, 3);
SELECT* FROM WATCH;


INSERT INTO POST_COMMENT
VALUE(POST_COMMENT_NUMBER, POST_COMMENT_CONTENT, POST_COMMENT_DATE, BOARD_NUMBER, MEMBER_NUMBER)
VALUES(POST_COMMENT_NUMBER_SEQ.NEXTVAL, '나도..', SYSDATE, 1, 2);
INSERT INTO POST_COMMENT
VALUES(POST_COMMENT_NUMBER_SEQ.NEXTVAL, '반갑습니다~!!', SYSDATE, 2, 3);
INSERT INTO POST_COMMENT
VALUES(POST_COMMENT_NUMBER_SEQ.NEXTVAL, '국밥 ㄱㄱ', SYSDATE, 3, 1);
INSERT INTO POST_COMMENT
VALUES(POST_COMMENT_NUMBER_SEQ.NEXTVAL, '칼국수 어떰?', SYSDATE, 3, 3);
INSERT INTO POST_COMMENT
VALUES(POST_COMMENT_NUMBER_SEQ.NEXTVAL, '광고 신고함', SYSDATE, 5, 4);
SELECT* FROM POST_COMMENT;


INSERT INTO ACTOR
VALUE(ACTOR_NUMBER, ACTOR_NAME)
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '박보영');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '이병헌');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '박서준');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '김선영');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '김도윤');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '박지후');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '정유미');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '이선균');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '레아 루이스');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '마무두 아티');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '신혜선');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '김성균');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '임철수');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '이주영');
INSERT INTO ACTOR
VALUES(ACTOR_NUMBER_SEQ.NEXTVAL, '강태오');
SELECT* FROM ACTOR;


INSERT INTO DIRECTOR
VALUE(DIRECTOR_NUMBER, DIRECTOR_NAME)
VALUES(DIRECTOR_NUMBER_SEQ.NEXTVAL, '유재선');
INSERT INTO DIRECTOR
VALUES(DIRECTOR_NUMBER_SEQ.NEXTVAL, '엄태화');
INSERT INTO DIRECTOR
VALUES(DIRECTOR_NUMBER_SEQ.NEXTVAL, '피터손');
INSERT INTO DIRECTOR
VALUES(DIRECTOR_NUMBER_SEQ.NEXTVAL, '박희곤');
SELECT* FROM DIRECTOR;


INSERT INTO CAST_MEMBER
VALUE(CAST_MEMBER_NUMBER, MOVIE_NUMBER, ACTOR_NUMBER, DIRECTOR_NUMBER)
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 1, 7, 1);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 1, 8, 1);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 1, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 2, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 3, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 4, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 5, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 2, 6, 2);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 3, 9, 3);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 3, 10, 3);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 4, 1, 4);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 4, 2, 4);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 4, 3, 4);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 4, 4, 4);
INSERT INTO CAST_MEMBER
VALUES(CAST_MEMBER_NUMBER_SEQ.NEXTVAL, 4, 5, 4);
SELECT* FROM CAST_MEMBER;


INSERT INTO RATING
VALUE(RATING_NUMBER, RATING_GRADE, MOVIE_NUMBER, MEMBER_NUMBER)
VALUES(RATING_NUMBER_SEQ.NEXTVAL, 3.5, 1, 1);
INSERT INTO RATING
VALUES(RATING_NUMBER_SEQ.NEXTVAL, 4, 1, 2);
INSERT INTO RATING
VALUES(RATING_NUMBER_SEQ.NEXTVAL, 3, 2, 2);
INSERT INTO RATING
VALUES(RATING_NUMBER_SEQ.NEXTVAL, 3.8, 3, 3);
SELECT* FROM RATING;


INSERT INTO LINE_REVIEW
VALUE(LINE_REVIEW_NUMBER, LINE_REVIEW_CONTEXT, MEMBER_NUMBER, MOVIE_NUMBER)
VALUES(LINE_REVIEW_NUMBER_SEQ.NEXTVAL, '재밌음', 1, 1);
INSERT INTO LINE_REVIEW
VALUES(LINE_REVIEW_NUMBER_SEQ.NEXTVAL, '좀 무서웠어요', 2, 1);
INSERT INTO LINE_REVIEW
VALUES(LINE_REVIEW_NUMBER_SEQ.NEXTVAL, '추천안함 시간낭비임;;', 2, 2);
INSERT INTO LINE_REVIEW
VALUES(LINE_REVIEW_NUMBER_SEQ.NEXTVAL, '킬링 타임용 영화', 4, 3);
INSERT INTO LINE_REVIEW
VALUES(LINE_REVIEW_NUMBER_SEQ.NEXTVAL, '별로..', 3, 4);
SELECT* FROM LINE_REVIEW;


INSERT INTO BASKET
VALUE(BASKET_NO, MEMBER_NUMBER, MOVIE_NUMBER)
VALUES(BASKET_NUMBER_SEQ.NEXTVAL, 1, 1);
INSERT INTO BASKET
VALUES(BASKET_NUMBER_SEQ.NEXTVAL, 1, 2);
INSERT INTO BASKET
VALUES(BASKET_NUMBER_SEQ.NEXTVAL, 2, 3);
INSERT INTO BASKET
VALUES(BASKET_NUMBER_SEQ.NEXTVAL, 3, 4);
SELECT* FROM BASKET;


INSERT ALL
    INTO ORDER_HISTORY
        VALUES(to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), SYSDATE, 1)
    INTO ORDER_PRODUCT
        VALUES(ORDER_PRODUCT_NUMBER_SEQ.NEXTVAL, to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), 1)
SELECT * FROM DUAL;
INSERT ALL
    INTO ORDER_HISTORY
        VALUES(to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), SYSDATE, 1)
    INTO ORDER_PRODUCT
        VALUES(ORDER_PRODUCT_NUMBER_SEQ.NEXTVAL, to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), 1)
SELECT * FROM DUAL;
INSERT ALL
    INTO ORDER_HISTORY
        VALUES(to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), SYSDATE, 3)
    INTO ORDER_PRODUCT
        VALUES(ORDER_PRODUCT_NUMBER_SEQ.NEXTVAL, to_number(to_char(sysdate, 'yymmdd')) || LPAD(ORDER_HISTORY_NUMBER_SEQ.NEXTVAL, 3, '0'), 1)
SELECT * FROM DUAL;